default:	
		gcc -Wall -Werror -pedantic meminfo.c -o meminfo
		gcc -Wall -Werror -pedantic cpuinfo.c -o cpuinfo
		gcc -Wall -Werror -pedantic arreglos.c -o arreglos
		
clean:
		rm -f arreglos cpuinfo meminfo